package pl.taurus.reviseo.review.application.domain.service

import org.springframework.stereotype.Service
import pl.taurus.reviseo.persona.application.port.incoming.GetAllPersonasUseCase
import pl.taurus.reviseo.review.application.port.incoming.GenerateCodeReviewPromptUseCase

@Service
class GenerateCodeReviewPromptService(
    private val getAllPersonasUseCase: GetAllPersonasUseCase,
) : GenerateCodeReviewPromptUseCase {
    override fun generate(command: GenerateCodeReviewPromptUseCase.Command): String {
        val personas =
            getAllPersonasUseCase
                .getAll()
                .filter { it.identifier.value in command.personasIdentifiers }
                .toList()

        require(personas.isNotEmpty()) { "No personas found for identifiers: ${command.personasIdentifiers}" }

        val prompt =
            CodeReviewPromptBuilder()
                .addGeneralInstruction("You are an experienced software engineer and code reviewer.")
                .addGeneralInstruction(
                    "Your task is to perform a **pending code review** for the Pull Request provided below. " +
                        "Do NOT submit or approve the review — generate review comments only.",
                ).addGeneralInstruction(
                    """
                    ---
                    
                    ## Pull Request
                    URL: ${command.pullRequestUrl}
                    
                    Assume:
                    - The code compiles and passes basic static analysis.
                    - Formatting, naming conventions, and trivial null checks are already handled by tools
                    
                    Avoid:
                    - Style nitpicks
                    - Obvious or mechanical comments
                    - Repeating what linters or IDEs would flag
                    """.trimIndent(),
                ).addGeneralInstruction(
                    """
                    ## Review Process

                    You will review the code using multiple expert personas.
                    Each persona works independently and focuses on its own perspective.
                    For each persona finding create a comment.
                    """.trimIndent(),
                ).addGeneralInstruction(
                    """
                    ### Comment format (MANDATORY)

                    Every comment MUST follow this format:
                    [AI Generated by {{Persona Name}} persona]
                    # Context
                    What part of the code or design this comment refers to.

                    # Observation
                    What you noticed. Be specific and factual.

                    # Why it matters
                    Explain the impact (maintenance, scalability, correctness, operability, etc.).

                    # Suggestion
                    Concrete recommendation or alternative approach.
                    
                    Keep comments concise but meaningful.
                    Prefer fewer, high-quality comments over many shallow ones.
                    """.trimIndent(),
                ).addPersonas(personas)
                .addStep(
                    "Final consolidation",
                    """
                    After all personas have generated their comments:

                    1. Review all generated comments.
                    2. Detect comments that:
                       - Address the same underlying issue, OR
                       - Strongly overlap in intent or recommendation.
                    3. Merge such comments into a **single, stronger comment**.
                    4. When merging:
                       - Preserve the most insightful reasoning.
                       - Mention all relevant personas in the header, e.g.
                         `[AI Generated by Software Architect + Security Reviewer personas]`
                    5. Remove redundant or low-value comments.
                    """.trimIndent(),
                ).build()

        return prompt
    }
}
