version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      security-fixes:
        applies-to: security-updates
        patterns:
          - "*"
      versions-updates:
        applies-to: version-updates
        patterns:
          - "*"