import type { PromptComponent } from './PromptComponent';

const COMMENT_FORMAT =
`### Comment format (MANDATORY)

Every comment must start with this information:
**[AI Generated by <persona name> persona]**
**<Short title of the comment>**

Keep comments concise but meaningful.
Prefer fewer, high-quality comments over many shallow ones.`;

export class CommentFormatComponent implements PromptComponent {
    getText(): string {
        return COMMENT_FORMAT;
    }
}
