import type { StepsComponent } from './StepsComponent';
import { PhaseComponent } from './PhaseComponent';

export class SingleAgentPhaseComponent extends PhaseComponent {
    protected readonly instructions =
`## Review Process
Do NOT submit or approve the review — generate review comments only.

You will review the code using multiple expert personas.
Each persona works independently and focuses on its own perspective.
For each Step below, adopt that persona and perform your review according to its checklist.
Use available tools to:
- Fetch the pull request diff
- Create a new pending review
- Add comments to the pending review

If any operation fails, report the error and stop — do not continue with partial data.`;

    protected readonly finalStep =
`Final Step: Final consolidation and comment submission
After all personas have generated their comments:

1. Review all generated comments.
2. Detect comments that:
    - Address the same underlying issue, OR
    - Strongly overlap in intent or recommendation.
3. Merge such comments into a **single, stronger comment**.
4. When merging:
    - Preserve the most insightful reasoning.
    - Mention all relevant personas in the header, e.g.
      \`**[AI Generated by Software Architect + Security Reviewer personas]**\`
      \`**Memory Leak in Connection Pool**\`
5. Remove redundant or low-value comments.
6. Create a pending review on the pull request. Do not add a review body — leave it empty.
7. Add prepared comments to the pull request.
   Format each comment, see Comment format section`;

    constructor(stepsComponent: StepsComponent) {
        super(stepsComponent);
    }
}
