import type { PromptComponent } from './PromptComponent';
import { CommentFormatComponent } from './CommentFormatComponent';

export class ValidateCommentsPhase implements PromptComponent {
    constructor(private readonly phaseNumber: number) {}

    getText(): string {
        const instructions =
`## Phase ${this.phaseNumber}: Validate Comments

Deduplicate and validate the collected review comments:

1. Detect comments that address the same underlying issue or strongly overlap in intent or recommendation.
2. Merge such comments into a **single, stronger comment**:
   - Preserve the most insightful reasoning from each.
   - Mention all relevant personas in the header, e.g.
     \`**[AI Generated by Software Architect + Security Reviewer personas]**\`
     \`**Memory Leak in Connection Pool**\`
   - Use the most specific file/line reference.
   - A comment is redundant only if its entire body is already covered by the merged comment.
   - When in doubt, keep both comments rather than dropping one.
3. Remove any remaining redundant or low-value comments.
4. Verify that every remaining comment conforms to the comment format:`;

        return [
            instructions,
            new CommentFormatComponent().getText(),
        ].join('\n\n');
    }
}
