import type { PromptOptions, Persona } from './types';

interface ReviewProcess {
    readonly instructions: string;
    readonly finalStep: string;
}

const ROLE =
`You are an experienced software engineer and code reviewer.
Your task is to perform a **pending code review** for the Pull Request provided below.
---`;

const ASSUMPTIONS =
`Assume:
- The code compiles and passes basic static analysis.
- Formatting, naming conventions, and trivial null checks are already handled by tools

Avoid:
- Style nitpicks
- Obvious or mechanical comments
- Repeating what linters or IDEs would flag`;

const COMMENT_FORMAT =
`### Comment format (MANDATORY)

Every comment must start with this information:
**[AI Generated by {{Persona Name}} persona]**
**<Short title of the comment>**

Keep comments concise but meaningful.
Prefer fewer, high-quality comments over many shallow ones.`;

const SINGLE_AGENT_REVIEW_PROCESS: ReviewProcess = {
    instructions:
`## Review Process
Do NOT submit or approve the review — generate review comments only.

You will review the code using multiple expert personas.
Each persona works independently and focuses on its own perspective.
Use available tools to:
- Fetch the pull request diff
- Create a new pending review
- Add comments to the pending review

If any operation fails, report the error and stop — do not continue with partial data.`,

    finalStep:
`Final Step: Final consolidation and comment submission
After all personas have generated their comments:

1. Review all generated comments.
2. Detect comments that:
    - Address the same underlying issue, OR
    - Strongly overlap in intent or recommendation.
3. Merge such comments into a **single, stronger comment**.
4. When merging:
    - Preserve the most insightful reasoning.
    - Mention all relevant personas in the header, e.g.
      \`**[AI Generated by Software Architect + Security Reviewer personas]**\`
      \`**Memory Leak in Connection Pool**\`
5. Remove redundant or low-value comments.
6. Create a pending review on the pull request.
7. Add prepared comments to the pull request.`,
};

const MULTI_AGENT_REVIEW_PROCESS: ReviewProcess = {
    instructions:
`## Review Process
You are running in multi-agent orchestration mode. Your role is to coordinate subagents — you do not perform code review yourself.

1. Fetch the pull request diff using available tools.
   Store the diff — it will be passed to all subagents.

2. For each persona step below, launch a subagent with:
   - The full PR diff.
   - That persona's instructions and checklist.
   - The JSON output format specified in the Final Step.

   If any subagent call fails, report the error and stop.

3. Each subagent must return ONLY a JSON array. No prose, no markdown fences.
   Every element must conform to:
   {
     "persona": "<persona name>",
     "file": "<path/to/file.ext>",
     "line": <integer line number, or null for file-level comments>,
     "title": "<short comment title>",
     "body": "<full comment text>"
   }`,

    finalStep:
`Final Step: Aggregate and submit
After all subagents have returned:

1. Parse each subagent's JSON array.
2. Merge two comments if they reference the same file AND the same line AND their titles address the same root concern.
   When merging:
   - Combine the most insightful reasoning from each.
   - Set "persona" to a combined label, e.g. "Security Auditor + Performance Reviewer".
   - Use the most specific file/line reference.
   A comment is redundant only if its entire body is already covered by the merged comment.
   When in doubt, keep both comments rather than dropping one.
3. Create a pending review and submit all comments using available tools.
   Format each comment using the Comment format above:
     **[AI Generated by <persona> persona]**
     **<title>**
     <body>

   If any operation fails, report the error and stop — do not submit a partial review.`,
};

function buildPrContext(prUrl: string): string {
    return `## Pull Request
URL: ${prUrl}`;
}

function buildPersonaStep(persona: Persona, stepNumber: number): string {
    const checklistLines = persona.checklist.length > 0
        ? persona.checklist.map(item => `- ${item}`).join('\n')
        : '- (no checklist items)';

    return `### Step ${stepNumber}: ${persona.name}
${persona.customInstructions}

Checklist:
${checklistLines}`;
}

class PromptBuilder {
    private reviewProcess: ReviewProcess = SINGLE_AGENT_REVIEW_PROCESS;

    constructor(private readonly prUrl: string, private readonly personas: Persona[]) {}

    withReviewProcess(reviewProcess: ReviewProcess): this {
        this.reviewProcess = reviewProcess;
        return this;
    }

    build(): string {
        const personaSteps = this.personas
            .map((persona, index) => buildPersonaStep(persona, index + 1))
            .join('\n\n');

        return [
            ROLE,
            buildPrContext(this.prUrl),
            ASSUMPTIONS,
            this.reviewProcess.instructions,
            COMMENT_FORMAT,
            personaSteps,
            this.reviewProcess.finalStep,
        ].join('\n\n');
    }
}

const DEFAULT_PROMPT_OPTIONS: PromptOptions = { multiAgent: false };

export function buildPrompt(prUrl: string, personas: Persona[], settings: PromptOptions = DEFAULT_PROMPT_OPTIONS): string {
    if (personas.length === 0) {
        return '';
    }

    const builder = new PromptBuilder(prUrl, personas);
    if (settings.multiAgent) {
        builder.withReviewProcess(MULTI_AGENT_REVIEW_PROCESS);
    }
    return builder.build();
}
